<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tukar_Button</name>
   <tag></tag>
   <elementGuidId>057977a0-8456-47d2-8afa-1bbaf0c3cf20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.TextView[@text='mon']/following-sibling::android.view.ViewGroup/android.widget.TextView</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.TextView[@text='mon']/following-sibling::android.view.ViewGroup/android.widget.TextView</value>
   </webElementProperties>
</WebElementEntity>
