<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JenisPerawatan_DropdownText</name>
   <tag></tag>
   <elementGuidId>29d0ee37-df5b-41c3-a187-14b8a507e435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.TextView[@text=&quot;Pemangkasan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.TextView[@text=&quot;Pemangkasan&quot;]</value>
   </webElementProperties>
</WebElementEntity>
