<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LongLat_Field</name>
   <tag></tag>
   <elementGuidId>c36d6fa5-43b2-4e7c-87b0-fee353d3d22b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//android.view.ViewGroup)[25]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//android.view.ViewGroup)[25]</value>
   </webElementProperties>
</WebElementEntity>
