<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_Button</name>
   <tag></tag>
   <elementGuidId>13fdec83-a72a-49b2-b77d-d6bd02bcceb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//android.view.ViewGroup[2]/android.view.ViewGroup)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//android.view.ViewGroup[2]/android.view.ViewGroup)[1]</value>
   </webElementProperties>
</WebElementEntity>
