<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_Button</name>
   <tag></tag>
   <elementGuidId>0b4c3296-b30e-4902-b803-35954ab80f0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//android.widget.ImageView)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//android.widget.ImageView)[2]</value>
   </webElementProperties>
</WebElementEntity>
