<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tampilkan_Button</name>
   <tag></tag>
   <elementGuidId>6808741a-7d41-43b4-b64a-335c04cdf30c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.TextView[contains(@text,&quot;Tampilkan&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.TextView[contains(@text,&quot;Tampilkan&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
