<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>KebutuhanBahan_Textfield</name>
   <tag></tag>
   <elementGuidId>6e717cbb-9876-46d8-b795-b1f6052f5304</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//android.widget.EditText)[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//android.widget.EditText)[3]</value>
   </webElementProperties>
</WebElementEntity>
