<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Komentar_Text</name>
   <tag></tag>
   <elementGuidId>e677cf1e-509d-4380-98c0-52c3453d1459</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//android.widget.TextView[@text=&quot;Komentar&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//android.widget.TextView[@text=&quot;Komentar&quot;])[1]</value>
   </webElementProperties>
</WebElementEntity>
