<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>KelurahanDesa_ListField</name>
   <tag></tag>
   <elementGuidId>bef4f4a9-f479-4209-8c3e-e702c19ef08b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.view.ViewGroup[5]/android.view.ViewGroup/android.widget.EditText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.view.ViewGroup[5]/android.view.ViewGroup/android.widget.EditText</value>
   </webElementProperties>
</WebElementEntity>
