<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Komoditas_TextField</name>
   <tag></tag>
   <elementGuidId>fbd801db-6774-49ce-9a23-5e1ed1a93a6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.view.ViewGroup[4]/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.EditText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.view.ViewGroup[4]/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.EditText</value>
   </webElementProperties>
</WebElementEntity>
