<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lokasi_TextField</name>
   <tag></tag>
   <elementGuidId>997c8b40-af12-43eb-b2d9-c342e821270a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.view.ViewGroup[4]/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.EditText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.view.ViewGroup[4]/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.EditText</value>
   </webElementProperties>
</WebElementEntity>
