<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nama_TextField</name>
   <tag></tag>
   <elementGuidId>effb42e0-39a9-41c5-a1b6-2c4a753e1b91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.view.ViewGroup[2]/android.widget.EditText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.view.ViewGroup[2]/android.widget.EditText</value>
   </webElementProperties>
</WebElementEntity>
