<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Provinsi_ListField</name>
   <tag></tag>
   <elementGuidId>7ff3ee9c-8af7-499b-83d8-6f6a75da907a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.view.ViewGroup[2]/android.view.ViewGroup/android.widget.EditText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.view.ViewGroup[2]/android.view.ViewGroup/android.widget.EditText</value>
   </webElementProperties>
</WebElementEntity>
