<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_Icon</name>
   <tag></tag>
   <elementGuidId>a99f899c-2c1e-4d4e-b86f-4630a8b57223</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//android.view.ViewGroup[1]/android.view.ViewGroup[1]/android.view.ViewGroup)[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//android.view.ViewGroup[1]/android.view.ViewGroup[1]/android.view.ViewGroup)[4]</value>
   </webElementProperties>
</WebElementEntity>
